-- ==============================================================================
-- REALM OF KINGDOMS: Authoritative Telemetry & Metrics Schema
-- Supabase Cloud (PostgreSQL)
-- ==============================================================================

CREATE TABLE IF NOT EXISTS public.game_telemetry (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id TEXT NOT NULL,
    player_id TEXT,
    player_email TEXT,
    event_name TEXT NOT NULL,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Fast lookup and aggregation indexes for metrics & analytics
CREATE INDEX IF NOT EXISTS idx_game_telemetry_created_at ON public.game_telemetry(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_game_telemetry_event_name ON public.game_telemetry(event_name);
CREATE INDEX IF NOT EXISTS idx_game_telemetry_session_id ON public.game_telemetry(session_id);
CREATE INDEX IF NOT EXISTS idx_game_telemetry_player_id ON public.game_telemetry(player_id);

-- Enable Row Level Security (RLS)
ALTER TABLE public.game_telemetry ENABLE ROW LEVEL SECURITY;

-- Allow anonymous or authenticated players to insert their gameplay metrics
CREATE POLICY "Allow public insert to game_telemetry" 
ON public.game_telemetry 
FOR INSERT 
WITH CHECK (true);

-- Allow reading metrics only via service role (admin / backend)
CREATE POLICY "Allow read only for service role" 
ON public.game_telemetry 
FOR SELECT 
USING (auth.role() = 'service_role');
