import { createClient } from '@supabase/supabase-js'

const SUPABASE_URL = 'https://hoghpltpvqfdpxcepqlr.supabase.co'
const SUPABASE_ANON_KEY = 'sb_publishable_BtISgMp6lgm6kD6vXCQWzw_WheXO0cf'

const supabase = createClient(SUPABASE_URL, SUPABASE_ANON_KEY)

const COMPETITORS = [
  // GRANDMASTER TIER (Top 3 Contenders)
  {
    id: 'lb_kaiser_vane',
    player_name: 'Kaiser Vane',
    kingdom_name: 'Imperio Dracónico',
    level: 15,
    trophies: 2940,
    military_power: 194500,
    avatar: '/assets/avatars/avatar_king.webp',
    league_id: 'league_grandmaster',
    dungeon_floor: 25,
    dungeon_stars: 75,
    arena_wins: 482,
    updated_at: new Date(Date.now() - 1000 * 60 * 12).toISOString(),
  },
  {
    id: 'lb_valkyrie_freya',
    player_name: 'Valkyrie Freya',
    kingdom_name: 'Valhalla del Norte',
    level: 14,
    trophies: 2880,
    military_power: 182300,
    avatar: '/assets/avatars/avatar_valkyrie.webp',
    league_id: 'league_grandmaster',
    dungeon_floor: 24,
    dungeon_stars: 72,
    arena_wins: 456,
    updated_at: new Date(Date.now() - 1000 * 60 * 25).toISOString(),
  },
  {
    id: 'lb_archon_darius',
    player_name: 'Archon Darius',
    kingdom_name: 'Sol Invictus',
    level: 13,
    trophies: 2815,
    military_power: 168900,
    avatar: '/assets/avatars/avatar_paladin.webp',
    league_id: 'league_grandmaster',
    dungeon_floor: 23,
    dungeon_stars: 69,
    arena_wins: 430,
    updated_at: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
  },

  // MASTER TIER
  {
    id: 'lb_lady_morgana',
    player_name: 'Lady Morgana',
    kingdom_name: 'Corte de las Sombras',
    level: 12,
    trophies: 2650,
    military_power: 148200,
    avatar: '/assets/avatars/avatar_mage.webp',
    league_id: 'league_master',
    dungeon_floor: 21,
    dungeon_stars: 63,
    arena_wins: 395,
    updated_at: new Date(Date.now() - 1000 * 60 * 80).toISOString(),
  },
  {
    id: 'lb_duke_ragnar',
    player_name: 'Duke Ragnar',
    kingdom_name: 'Bastión de Hierro',
    level: 11,
    trophies: 2520,
    military_power: 132400,
    avatar: '/assets/avatars/avatar_assassin.webp',
    league_id: 'league_master',
    dungeon_floor: 19,
    dungeon_stars: 57,
    arena_wins: 360,
    updated_at: new Date(Date.now() - 1000 * 60 * 110).toISOString(),
  },
  {
    id: 'lb_queen_maeve',
    player_name: 'Queen Maeve',
    kingdom_name: 'Reino Celestial',
    level: 11,
    trophies: 2410,
    military_power: 124800,
    avatar: '/assets/avatars/avatar_valkyrie.webp',
    league_id: 'league_master',
    dungeon_floor: 18,
    dungeon_stars: 54,
    arena_wins: 342,
    updated_at: new Date(Date.now() - 1000 * 60 * 140).toISOString(),
  },
  {
    id: 'lb_inquisitor_malakor',
    player_name: 'Inquisitor Malakor',
    kingdom_name: 'Fortaleza del Ocaso',
    level: 10,
    trophies: 2310,
    military_power: 112600,
    avatar: '/assets/avatars/avatar_king.webp',
    league_id: 'league_master',
    dungeon_floor: 17,
    dungeon_stars: 51,
    arena_wins: 318,
    updated_at: new Date(Date.now() - 1000 * 60 * 180).toISOString(),
  },
  {
    id: 'lb_general_zheng',
    player_name: 'General Zheng',
    kingdom_name: 'Dinastía Jade',
    level: 10,
    trophies: 2205,
    military_power: 105400,
    avatar: '/assets/avatars/avatar_paladin.webp',
    league_id: 'league_master',
    dungeon_floor: 16,
    dungeon_stars: 48,
    arena_wins: 295,
    updated_at: new Date(Date.now() - 1000 * 60 * 210).toISOString(),
  },
  {
    id: 'lb_high_king_thorin',
    player_name: 'High King Thorin',
    kingdom_name: 'Ciudadela de Piedra',
    level: 9,
    trophies: 2090,
    military_power: 96800,
    avatar: '/assets/avatars/avatar_king.webp',
    league_id: 'league_master',
    dungeon_floor: 15,
    dungeon_stars: 45,
    arena_wins: 278,
    updated_at: new Date(Date.now() - 1000 * 60 * 240).toISOString(),
  },

  // GOLD TIER
  {
    id: 'lb_baron_von_steele',
    player_name: 'Baron Von Steele',
    kingdom_name: 'Marquesado Gris',
    level: 8,
    trophies: 1920,
    military_power: 84300,
    avatar: '/assets/avatars/avatar_assassin.webp',
    league_id: 'league_gold',
    dungeon_floor: 14,
    dungeon_stars: 42,
    arena_wins: 245,
    updated_at: new Date(Date.now() - 1000 * 60 * 280).toISOString(),
  },
  {
    id: 'lb_prince_cassian',
    player_name: 'Prince Cassian',
    kingdom_name: 'Corona de Plata',
    level: 8,
    trophies: 1810,
    military_power: 76500,
    avatar: '/assets/avatars/avatar_valkyrie.webp',
    league_id: 'league_gold',
    dungeon_floor: 13,
    dungeon_stars: 39,
    arena_wins: 228,
    updated_at: new Date(Date.now() - 1000 * 60 * 310).toISOString(),
  },
  {
    id: 'lb_archmage_solon',
    player_name: 'Archmage Solon',
    kingdom_name: 'Torre Arcana',
    level: 7,
    trophies: 1720,
    military_power: 68900,
    avatar: '/assets/avatars/avatar_mage.webp',
    league_id: 'league_gold',
    dungeon_floor: 12,
    dungeon_stars: 36,
    arena_wins: 210,
    updated_at: new Date(Date.now() - 1000 * 60 * 350).toISOString(),
  },
  {
    id: 'lb_commander_tiberius',
    player_name: 'Commander Tiberius',
    kingdom_name: 'Legión Imperial',
    level: 7,
    trophies: 1610,
    military_power: 61400,
    avatar: '/assets/avatars/avatar_paladin.webp',
    league_id: 'league_gold',
    dungeon_floor: 11,
    dungeon_stars: 33,
    arena_wins: 194,
    updated_at: new Date(Date.now() - 1000 * 60 * 380).toISOString(),
  },
  {
    id: 'lb_sovereign_helios',
    player_name: 'Sovereign Helios',
    kingdom_name: 'Reino de la Aurora',
    level: 6,
    trophies: 1520,
    military_power: 54200,
    avatar: '/assets/avatars/avatar_king.webp',
    league_id: 'league_gold',
    dungeon_floor: 10,
    dungeon_stars: 30,
    arena_wins: 178,
    updated_at: new Date(Date.now() - 1000 * 60 * 420).toISOString(),
  },
  {
    id: 'lb_paladin_galahad',
    player_name: 'Paladin Galahad',
    kingdom_name: 'Orden del Santo Trono',
    level: 6,
    trophies: 1430,
    military_power: 48600,
    avatar: '/assets/avatars/avatar_paladin.webp',
    league_id: 'league_gold',
    dungeon_floor: 9,
    dungeon_stars: 27,
    arena_wins: 162,
    updated_at: new Date(Date.now() - 1000 * 60 * 450).toISOString(),
  },

  // SILVER TIER
  {
    id: 'lb_lord_aethelgard',
    player_name: 'Lord Aethelgard',
    kingdom_name: 'Valle de los Vientos',
    level: 5,
    trophies: 1320,
    military_power: 41200,
    avatar: '/assets/avatars/avatar_king.webp',
    league_id: 'league_silver',
    dungeon_floor: 8,
    dungeon_stars: 24,
    arena_wins: 142,
    updated_at: new Date(Date.now() - 1000 * 60 * 490).toISOString(),
  },
  {
    id: 'lb_warlord_kaelen',
    player_name: 'Warlord Kaelen',
    kingdom_name: 'Estepas Rojas',
    level: 5,
    trophies: 1210,
    military_power: 35800,
    avatar: '/assets/avatars/avatar_assassin.webp',
    league_id: 'league_silver',
    dungeon_floor: 7,
    dungeon_stars: 21,
    arena_wins: 126,
    updated_at: new Date(Date.now() - 1000 * 60 * 530).toISOString(),
  },
  {
    id: 'lb_centurion_markus',
    player_name: 'Centurion Markus',
    kingdom_name: 'Bastión Fronterizo',
    level: 4,
    trophies: 1100,
    military_power: 29500,
    avatar: '/assets/avatars/avatar_paladin.webp',
    league_id: 'league_silver',
    dungeon_floor: 6,
    dungeon_stars: 18,
    arena_wins: 110,
    updated_at: new Date(Date.now() - 1000 * 60 * 570).toISOString(),
  },
  {
    id: 'lb_sorceress_lyra',
    player_name: 'Sorceress Lyra',
    kingdom_name: 'Círculo de Cristal',
    level: 4,
    trophies: 980,
    military_power: 24200,
    avatar: '/assets/avatars/avatar_mage.webp',
    league_id: 'league_silver',
    dungeon_floor: 5,
    dungeon_stars: 15,
    arena_wins: 94,
    updated_at: new Date(Date.now() - 1000 * 60 * 610).toISOString(),
  },
  {
    id: 'lb_marshal_boran',
    player_name: 'Marshal Boran',
    kingdom_name: 'Colinas de Bronce',
    level: 3,
    trophies: 860,
    military_power: 19800,
    avatar: '/assets/avatars/avatar_king.webp',
    league_id: 'league_silver',
    dungeon_floor: 4,
    dungeon_stars: 12,
    arena_wins: 78,
    updated_at: new Date(Date.now() - 1000 * 60 * 650).toISOString(),
  },

  // BRONZE TIER (Beginners & Climbers)
  {
    id: 'lb_novice_alaric',
    player_name: 'Novice Alaric',
    kingdom_name: 'Feudo del Bosque',
    level: 3,
    trophies: 740,
    military_power: 15400,
    avatar: '/assets/avatars/avatar_valkyrie.webp',
    league_id: 'league_bronze',
    dungeon_floor: 3,
    dungeon_stars: 9,
    arena_wins: 62,
    updated_at: new Date(Date.now() - 1000 * 60 * 700).toISOString(),
  },
  {
    id: 'lb_baroness_elena',
    player_name: 'Baroness Elena',
    kingdom_name: 'Colinas Verdes',
    level: 2,
    trophies: 620,
    military_power: 11200,
    avatar: '/assets/avatars/avatar_mage.webp',
    league_id: 'league_bronze',
    dungeon_floor: 3,
    dungeon_stars: 8,
    arena_wins: 48,
    updated_at: new Date(Date.now() - 1000 * 60 * 750).toISOString(),
  },
  {
    id: 'lb_lord_cedric',
    player_name: 'Lord Cedric',
    kingdom_name: 'Tierras Altas',
    level: 2,
    trophies: 530,
    military_power: 7800,
    avatar: '/assets/avatars/avatar_assassin.webp',
    league_id: 'league_bronze',
    dungeon_floor: 2,
    dungeon_stars: 6,
    arena_wins: 36,
    updated_at: new Date(Date.now() - 1000 * 60 * 800).toISOString(),
  },
  {
    id: 'lb_champion_garek',
    player_name: 'Champion Garek',
    kingdom_name: 'Vanguardia de Acero',
    level: 1,
    trophies: 460,
    military_power: 4900,
    avatar: '/assets/avatars/avatar_paladin.webp',
    league_id: 'league_bronze',
    dungeon_floor: 2,
    dungeon_stars: 4,
    arena_wins: 24,
    updated_at: new Date(Date.now() - 1000 * 60 * 850).toISOString(),
  },
  {
    id: 'lb_shield_ragnar',
    player_name: 'Shield Ragnar',
    kingdom_name: 'Costa Gris',
    level: 1,
    trophies: 420,
    military_power: 3600,
    avatar: '/assets/avatars/avatar_king.webp',
    league_id: 'league_bronze',
    dungeon_floor: 1,
    dungeon_stars: 3,
    arena_wins: 16,
    updated_at: new Date(Date.now() - 1000 * 60 * 900).toISOString(),
  },
]

async function seed() {
  console.log(`Upserting ${COMPETITORS.length} global competitors into Supabase leaderboard...`)
  const { data, error } = await supabase
    .from('leaderboard')
    .upsert(COMPETITORS, { onConflict: 'id' })

  if (error) {
    console.error('Error seeding leaderboard:', error)
  } else {
    console.log('Successfully seeded global leaderboard in Supabase!')
  }
}

seed()
